apiVersion: v1
data:
  root.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEVENDQXZXZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREJRTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVJzd0dRWURWUVFEREJKRgpiblJsY25CeWFYTmxJRkp2YjNRZ1EwRXdIaGNOTWpJd01UQTVNakl3TlRReldoY05Nekl3TVRBNU1qSXdOVFF6CldqQlhNUXN3Q1FZRFZRUUdFd0pWVXpFUE1BMEdBMVVFQ2d3R1IyOXZaMnhsTVJNd0VRWURWUVFMREFwRmJuUmwKY25CeWFYTmxNU0l3SUFZRFZRUUREQmxGYm5SbGNuQnlhWE5sSUZOMVltOXlaR2x1WVhSbElFTkJNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6UUVTdVlySjVVdlZ6Tmw2SzlITDJ3SWpLcGkxClptVU5ObERvbndJRy84T3FwcHY4TGw1NXVLNUxzUW5QRVBqaXU2ZHhlTzdMSC9ZTVpESVpNWVNuNjI2UUtTNmMKQlE2N1dXSHAyeHZiNHpYSXBqbndMdDZGWCsrcHM4eVpOd1BuVDZ5a3pVVWRUZ3ZEUEh6aXNjcXY4aUJpTkp2MAp6c21UOXN5Wk5mWHlGTU1RVlB2SWxFN2hCNDV4akdHbko1ekhTV3JJWHowaWs0Smg3SUJSaE00TE03a2k3dVZQCnE2MTk1Y0I2M0w5SEh3UnpmcGFHYnVzcHRFeW1SYm5qVFlFcnUveElISDcxSlJsQkpLSTZzNWZ4MWlhQXpPSHcKNCtiUU9zdmZjM2xyNW5zeURPUHVrdm5lM3JMU1VQa2dTWUx0bEV2UGV3cDM1d0hpWGxEc0VnTXM3d0lEQVFBQgpvNEhxTUlIbk1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkCkRnUVdCQlMzdXJBQ29lZStOTWJCQlZ4bWVPVzdVMTJoVkRBZkJnTlZIU01FR0RBV2dCUjhIRnZvUHJNekNaYVMKTXRoL1JML01qSk9ja2pCRkJnZ3JCZ0VGQlFjQkFRUTVNRGN3TlFZSUt3WUJCUVVITUFLR0tXaDBkSEE2THk5dwphMmt1WlhOdlpHVnRiMkZ3Y0RJdVkyOXRMMk5oTDNKdmIzUXRZMkV1WTJWeU1Eb0dBMVVkSHdRek1ERXdMNkF0Cm9DdUdLV2gwZEhBNkx5OXdhMmt1WlhOdlpHVnRiMkZ3Y0RJdVkyOXRMMk5oTDNKdmIzUXRZMkV1WTNKc01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUURDcnJBd2RlUlFNb3Z1MDB3czhJM3JlVUlNRWR0c0Z3TFJTaHUwZ2dWaApHSE1IMXZHRHBkUkpvYVNwQ0dkQ2NQdjFJQTBCa0w2OTY5ZGYxR0RVeFFPV2JpTGFqeVE1UzZmVkZnWi95SWJuCjNTek13N0R1YmlnMmk5eEpvOWxhUHBqampNL2dGNmJCU3hkaG9MVUtMRmYwZTgyRkN1QVBYc2tlaVc3QmMxWEIKM3VpNHhnUE5WejNUSHU4TWE5ei9mVEpSb2hyQzh0MUMvcGFiN1RRcGNRUjZYa1JyWDVTYi9NTTZUbkZldzdzRAo1Y3VGVDdvL0R2YldUNDIvVVAybnVOaTU5MVRJR1lESkJDS0JxbmQwQUg2UnorVlR5ZVJVVnA0ajIxRXh0ekwwCkpLbU4xUytkbVA1VzZQMUVWK3p0RWxsS0VWM04vZTZyNjU1d2xERy8weTdHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tpm_client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVHVENDQXdHZ0F3SUJBZ0lCSlRBTkJna3Foa2lHOXcwQkFRc0ZBREJYTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVNJd0lBWURWUVFEREJsRgpiblJsY25CeWFYTmxJRk4xWW05eVpHbHVZWFJsSUVOQk1CNFhEVEl5TURreE1URXlORE0xT1ZvWERUSTBNVEl4Ck9URXlORE0xT1Zvd1VqRUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQW9NQmtkdmIyZHNaVEVUTUJFR0ExVUUKQ3d3S1JXNTBaWEp3Y21selpURWRNQnNHQTFVRUF3d1VkSEJ0YzJsbmJtVnlRR1J2YldGcGJpNWpiMjB3Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUQ3Qms3WHR1TWszeW94UnZBZEc0QW9Dd01DCldESTV0STM0ai9HQUorUHpsR3lYTzd5bEtwcjNSUERDay9IZlRTajFCcHNla1BweVZwazlZa0NaRi9wNUNGV3EKRW5hV1lsUExBc2toNE5PUU9kQ0wvZzJTRnJ1RCtpaGhodTFlWDNFOTBROW1DbmZFdER5dDk5M1I1U0x0QnhnVgpFUm1GUXM0bVBlRjAxNVlRWmhONUZMTjNTcW05UEliRE1SQ2FxYXI0OHkrRnc0bjFObFFUa1p0dmNveDEzamJJCmJ3cEVZQit2dG1uSXZ6bE9abS84aWNPeEd0U25wcVJpRENzaXlpdG9wekZMM1BxMUtzS3ZDWHV4MnEyWFRHR0MKOGtzNW1lb0FUcUttcldhYkhxZ0pNdGxLWDJocHlEV0pCZ1BKVURQcFNOSWc2Ly9zUjJEY2trMEJXemRmQWdNQgpBQUdqZ2ZRd2dmRXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Ba0dBMVVkRXdRQ01BQXdFd1lEVlIwbEJBd3dDZ1lJCkt3WUJCUVVIQXdNd0hRWURWUjBPQkJZRUZHSUJPY245Ukc1cGpwQkIzQlNxL011WWVZMkhNQjhHQTFVZEl3UVkKTUJhQUZMZTZzQUtoNTc0MHhzRUZYR1o0NWJ0VFhhRlVNRVFHQ0NzR0FRVUZCd0VCQkRnd05qQTBCZ2dyQmdFRgpCUWN3QW9Zb2FIUjBjRG92TDNCcmFTNWxjMjlrWlcxdllYQndNaTVqYjIwdlkyRXZkR3h6TFdOaExtTmxjakE1CkJnTlZIUjhFTWpBd01DNmdMS0FxaGlob2RIUndPaTh2Y0d0cExtVnpiMlJsYlc5aGNIQXlMbU52YlM5allTOTAKYkhNdFkyRXVZM0pzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBc21TRlpXYll3dGtNQ2pYYnRVdGFCelZFRgp0TXlkc3p0R0VwRE0zaXdNZzFoZyt3T1kydXVYL2xBYmlwSm1vUk5HZnF3NzB5V1p1aHFqdGlzakJRb3JtRVZqCkFkU0d6Uk8yYWlxTnVwTjIwMDNDM2lJaUZVVTEvSGMxbXZxUnNha3BRc0U1clpmY0ZSMlZsanBtT1o3cWM2MjgKTnd6T3NBZWZVVS9SWXBXMUdxSnVhUXdOZGlCYVNPVjdOSXk2VFZBa29henBsS3NzWHZWc1ZIMStFb05JTTNjawpKYUdjQnNsay9JSkVDOTU5endsSlhPWkNmdGo2R1ZIRy80SFNVRDZhdEI3cmMrVWhVZFdxcUZtQ2RnWFVNUWQwCklRUkk5TGFKaktoNjNkNUp2QUdqNXQ0SVJ1dHFVNjZjS1lEWFdkcEtpQ0NmVCtjRDhuYSsrc1pLbU05RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tpm_client.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBK3daTzE3YmpKTjhxTVVid0hSdUFLQXNEQWxneU9iU04rSS94Z0Nmajg1UnNsenU4CnBTcWE5MFR3d3BQeDMwMG85UWFiSHBENmNsYVpQV0pBbVJmNmVRaFZxaEoybG1KVHl3TEpJZURUa0RuUWkvNE4Ka2hhN2cvb29ZWWJ0WGw5eFBkRVBaZ3AzeExROHJmZmQwZVVpN1FjWUZSRVpoVUxPSmozaGROZVdFR1lUZVJTegpkMHFwdlR5R3d6RVFtcW1xK1BNdmhjT0o5VFpVRTVHYmIzS01kZDQyeUc4S1JHQWZyN1pweUw4NVRtWnYvSW5ECnNSclVwNmFrWWd3cklzb3JhS2N4Uzl6NnRTckNyd2w3c2RxdGwweGhndkpMT1pucUFFNmlwcTFtbXg2b0NUTFoKU2w5b2FjZzFpUVlEeVZBejZValNJT3YvN0VkZzNKSk5BVnMzWHdJREFRQUJBb0lCQUZKWFg5NW5xZnVxem9MSwpnN0h3bHVuTHJ1bUNkN3N4REU3b0hLNU9wM243aW1GVFlZNkdPcjM0bWNjaDAzbk5yQzB2eFF0U1FDem9WaXpxCkFVbVdzWDBwTER4MUFQeFVkYXNHbDJackFzcnhCQVVmeVdETjN5V3NGYm5rRWhIZVdkMk9xYS90cUJyWWluMEEKYlAxUVhkUUZlek5SNEI2ejZyNWxsd0tHUXozT0w2N1poakRQVjlEYWtsS2t0V3htMWJnZmxnZ2JLaGp3Uzl3RwpPME1YZk9acEpwcngrSXVTZlQ5RFg5SUNYOW5HelQ0RThyNDJZS1MyK1JZazh0WmNTeksrcnhFeldaeGEzY2pPCkZObnlXdEFtd2xLbkkwQVBUSWhnUXFWRk9BQXZrNVd1SU5RazI2YlNJSnFBTEpxOFBIbFVKd3RHTmRKcVB1TXcKL1RKVWYvMENnWUVBL1JtYzVLc2lsY2xhNWNWYlZkZCtodG1ocm5LUmpIRGY2YjZCSjhSNnRGNjhUVHV3ckZtZgpPZlZ3cEpZWVdQSmlRQTlkSDJkdGZBSmgvMVRJNEh1S0ZFUVJEZ2dnZG9YcnErbllRcjEvb0pyUFJGaVEvMUFiCmRnSWY0TWppZlZCUHkzMU0wM2FIWnVXSUZtejFUMmsrWHM5UGFRd01Ld2J1Vm54ZWZvNC9HbFVDZ1lFQS9lYWIKaWRIOXdwU2FtVzdoYmIvcm9GemVlci9WbTlmazB1dHJEQmROTGZUeFpiODBVME96M2FhWHI5cC9kaDRBY3FDWQphOVFPaTBYYlloVndBZnFXNXRNRC9wKzZ2b2J5SXEwMTN1N1Q1azdQZEdDaWtVSVJXUHVQTDF1QlBqR3JLREorCmRLUzdhUkhRVWg0WktJVEMzeDJaVGprZFNoN01oS3puMVJwRlp1TUNnWUJ1TDE5WlFaT2Q1L24xZTlUR2F6ay8KRmJISWswSUFCUWZGNTlTc2JtSUk4aEZDQWxGb3h0K0Z5TzlRQjdQenpSbXV6OEYzc1h3OWQ0QVlPMTMwTkhRcApYSFNjU2pkdndkK1dpUWhJRGQxcEd0eE80Y3ZHQ3FiWjJoVHN0Q2U5N0YvQXMvemxObjI5OHdFcTJpWjFldGpYClI2TkhsU0lhL1RwM1ZrK0JBd1kvdlFLQmdENmlMOFpzNWdPbE13b2NuMEc2c1g2cXlqdFByWHMzWS94Z0ZOVXoKdmxkUzhHWGdLQ0ZPTjBXN2ZmbmtsY0xtbmNlcE5GQ05URlV4RTNCN3gxakZuNG9yamZXM0k1TXlxUExDOWVJYgoybXdiRHZRdmpvcjAyR0N5RmQxaDNsMGdWWStoL1MzN0lUeEhKN1BLTnZ5VzI1ZThybi9zZVB3NjRzcnIrSGpLCmRVcHZBb0dBQWgwU1JNSlMrZlJLU0FjTzY4bFRnTW4reUZ3OGUwZ1VCdHZxbW90dTEya3dxL0Z6UEpHM0d3TEYKeGJtbWxML21pcFRRRm1WYVlTaCs2RGFya2phbUg2QXRyeHlqT3lzRUhFb1hHNi9RUFVPUzFaTzRqQTU2QldORgpyUkZDMHlzc3NEVGw2VXZlclZVMkp4YnlPNE5JVE5HOVJ2WklibUI2SmV0amhZMHpvaEE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: default
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    type: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-service
  template:
    metadata:
      labels:
        name: app-service
        allowtpm: "true"
    spec:
      serviceAccountName: app-service-account
      automountServiceAccountToken: true
      containers:
      - name: app
        image: docker.io/salrashid123/tpmds-client@sha256:d21e15b5c66dc0de088db8113834b8fd3967c972dd165fb4998bd5076c212ee8
        command:
          - /bin/bash
          - -c
          - sleep 3600
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
      volumes:
      - name: certs
        secret:
          secretName: app-secrets
    

