apiVersion: v1
data:
  server_crt.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVNVENDQXhtZ0F3SUJBZ0lCUVRBTkJna3Foa2lHOXcwQkFRc0ZBREJNTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVJjd0ZRWURWUVFEREE1VAphVzVuYkdVZ1VtOXZkQ0JEUVRBZUZ3MHlOVEF4TVRneE9UTTFOVGRhRncwek5UQXhNVGd4T1RNMU5UZGFNRkV4CkN6QUpCZ05WQkFZVEFsVlRNUTh3RFFZRFZRUUtEQVpIYjI5bmJHVXhFekFSQmdOVkJBc01Da1Z1ZEdWeWNISnAKYzJVeEhEQWFCZ05WQkFNTUUyRjBkR1Z6ZEc5eUxtUnZiV0ZwYmk1amIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2xiN0Z3RHlLeGxkRWFWRHk4QkVicDR4dnZFbGwwRzNTR0JtVVlGWXpxCmZPWlNEaUlsSXZtZzdoZysySjNrVWdOMVZFNGVxVGtER2lmaTZDb2JPQ1ZUSlh6WFdFV0FtT3I1YUNQN2g0R24Kbkc5alMyUi9qcmVwczd5Z2h0aUR4ZjJudGtEd0E1bnJKcUFzbVZ1WmZVVi9ncUJWak5EUFd6NkJIS2FIdXNjaAp6WDFlanBrLzdyV1MxdnA5NTRwSW1wVWhxWTR0blVPS3Y1Z0NkUHRhODE4UjZESGhuL1ZwZlB4YlI1VGc1QW1FClpJeFVaaVJNL1RvamtaazBkdERKbXRQOFZJcUR3VGZtYjcxVUR4enFKbDFwOTJBV1J1U3d6QzY3ZDE2QmdyMTAKMHVhQnNmV0h1Q3RyWHNjZm1IVFV4eVBWWDluWUo0eERUNUtmcHJEZ2ZsOXRBZ01CQUFHamdnRVhNSUlCRXpBTwpCZ05WSFE4QkFmOEVCQU1DQjRBd0NRWURWUjBUQkFJd0FEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFkCkJnTlZIUTRFRmdRVW9oOXBkVWhuMEg0SkRFbkZDa3RjOVczQXZ4NHdId1lEVlIwakJCZ3dGb0FVN1BEcVUxTS8KbnlQY3dRNHhFRGNIM3Q3bmJ2TXdSUVlJS3dZQkJRVUhBUUVFT1RBM01EVUdDQ3NHQVFVRkJ6QUNoaWxvZEhSdwpPaTh2Y0d0cExtVnpiMlJsYlc5aGNIQXlMbU52YlM5allTOXliMjkwTFdOaExtTmxjakE2QmdOVkhSOEVNekF4Ck1DK2dMYUFyaGlsb2RIUndPaTh2Y0d0cExtVnpiMlJsYlc5aGNIQXlMbU52YlM5allTOXliMjkwTFdOaExtTnkKYkRBZUJnTlZIUkVFRnpBVmdoTmhkSFJsYzNSdmNpNWtiMjFoYVc0dVkyOXRNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBb2phcHM3YXdweXNteFVEcElTYUg5ZHgrMlZtbm9wcElKVjd6dGVzMGxScFZxZmc1VTBvdkhOQklNCjJlSlZMVHNSQUZkcWp3SlJjRlJzY2tCMmFTeWU3Z0FaY2hNVGVNamJFZ1lRb0dQUTBFcmxnNWtzSVd0TEttalAKcGFQL2g3Syt6QTdtamtVaTk1MHpCNnlpZmJkRlFzZk9GNTZXK0U4UW5RMkp5OWRiZ0p6UlhYWVpha3hYOVMzUQoreHNXQ01jRUFDMFN0aGJINCtOcEFTRW5jdGtHWmo2WWlEaFhjQUQ1bnc4c1E4a0VuR3R0YlJldnZZV3NQeEZDCmtlZVk0aXFTUnpTRlFiYlhTQXdqOG81cU8rMDVPcGRHdk1uUDljOGJzTGI3WW5DMmRiRDViSzVxZGY5QTBnZ0gKVndpUzMwZllyclVaTVIxRnZlblJQcXIzUytuWQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t 
  server_key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ2xiN0Z3RHlLeGxkRWEKVkR5OEJFYnA0eHZ2RWxsMEczU0dCbVVZRll6cWZPWlNEaUlsSXZtZzdoZysySjNrVWdOMVZFNGVxVGtER2lmaQo2Q29iT0NWVEpYelhXRVdBbU9yNWFDUDdoNEdubkc5alMyUi9qcmVwczd5Z2h0aUR4ZjJudGtEd0E1bnJKcUFzCm1WdVpmVVYvZ3FCVmpORFBXejZCSEthSHVzY2h6WDFlanBrLzdyV1MxdnA5NTRwSW1wVWhxWTR0blVPS3Y1Z0MKZFB0YTgxOFI2REhobi9WcGZQeGJSNVRnNUFtRVpJeFVaaVJNL1RvamtaazBkdERKbXRQOFZJcUR3VGZtYjcxVQpEeHpxSmwxcDkyQVdSdVN3ekM2N2QxNkJncjEwMHVhQnNmV0h1Q3RyWHNjZm1IVFV4eVBWWDluWUo0eERUNUtmCnByRGdmbDl0QWdNQkFBRUNnZ0VBRUUxVFZOR0kvNnJkc2hSKzc2QVVSTlBtV3NhYUhnRGVtSjVrczl6YngvZUsKMHFjbDRqYnlGbE9mL0FGb2Zhay9RZjZPdkNLOHhYdDhWclcrQUhTbDZPMld3Ym1uRDZjQjhKVzhoZnF5WWd2ZQpSaENWMUtRQm9TMWU5d3FTcDFtSlIwK0VVcUpvTm0zVjlzOGQ0YUFnaXhJYUxwUHp0NXNzSzVqaEtCclZxSlRvCnBvZzRSdXYzL1FCUnlRS05UalczOVhDU2FzQys1OXozUXgrUGlFK0ZmRWsxY1JBRFFJV2k4WDJleE1HdDBIZ2kKSkkvRENIR1JTTVkvYWdBb0RKRzE5dkV3T3V4clhxWmlDdE52Zk9oM2RicHpMT3ZPazVjTXZFZ3VZQktOTlFyNwpGRWRGYTNuRTB1ZEkxdEtJbjl3RUVsSVBWa0U0L0VZbG8yZDFzenRLR1FLQmdRRFNEdm15THpHYVgwdnFTSU9hCmZDdnRadXhmdld5L0tNVzhTYzNXcndOOHdlaFZObmhLMWhJV29FY2N6YWRva0tsbUhDUHE3OXR2Z3U2c0ZjbWMKbllOb1BmQlkrakF6OEU4eEFWWUYzWGlMNEppZC9xQ285azdXT29zVkpvL0Q0OGpTeVpCY0FHMnFBZmhUUk1hNApYTjV5aDNBV0NJajI3cW1VWWNtblk5K1phd0tCZ1FESm5scGNXMVUySGx6ajZyR2V2aDc0ZUswc0ZpaXVpVTRDCnVXbkEzSDZ0bVJIS1dBS2hIc0pkdDg3b1p2QzcwcGZzamZjOVppVnpBZ00rN2JLWHpPSkg5ajA0UlppeHRFRUcKcjVVVmMwVmo0ZTVoWk5TaUJva1JCS2NNT0J1WWRuajhyWDVlL1RiOWlqZnNyUEN0akVKSWoycjdYL2dMQVI2KwpDcHFpZVFOb2h3S0JnUUM4ejdFcHRMb0ZaSHM4VDRuYnBwbGxmd29nMUllWEcvTUExK1lwZm83SDZSUUk1RGtrCksxOSs3dnA4clc0NDB5OHhGVUpEdnUyalFqRitoT2IvMjZWdVlaNVVuQzRQd1lXdEt1SkR5MXE3Z0ZvdVNkM24KZ2Q1RE9jUWljdEx1NVNSeU03T0t2dWZUMUlsOWIyaWY5dm9NUUNsRDVOQVlCVlp3aGFWWXpMRURtUUtCZ1FDcwpzbjhqN1Blb1M0bTFrQ3BrbHVWZ1g3MjFyYVZiR3pFL0ZDS0ptRlRKemZ0M0hydmgxcjhXRjRPYmZkRm1rSlNoCmcxanJ0cnNOTUFRbnV1TG5OQS8vSStSOGR1QzhGbkk4ajlsYmJrbFpyUVRMVjlycWpqNkozVHBaTlJZdUdneTQKSXNQRUNaRTR5MVByM3BhcGtTS1ZsSU5Hbm9XUXAzejF1NCtJNjY4SHNRS0JnSFV2V203Q3g0TWZLNGlFU3FmegpEYURkN0NNbEp6VmhVOTlzMERUSVNVVVI0cW10QTlwYUlDS0dkb1NoRi9QTlNQNnhYaFFjVkJIWGRRZzh1dmIwCkJ1YkNiMTFWS3U4YnQ1STFoMVhiV0ZyWnZCL3p4SUhDbTJXT3M4VVdOSWU2SW00cURWZDJpK2lSb3JDdEJZN0UKd29zenNJaWpSbzFOVGJyYnYzajMvTms0Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  root.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkakNDQWw2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREJNTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVJjd0ZRWURWUVFEREE1VAphVzVuYkdVZ1VtOXZkQ0JEUVRBZUZ3MHlNekV5TWpjeE56TTRNREphRncwek16RXlNall4TnpNNE1ESmFNRXd4CkN6QUpCZ05WQkFZVEFsVlRNUTh3RFFZRFZRUUtEQVpIYjI5bmJHVXhFekFSQmdOVkJBc01Da1Z1ZEdWeWNISnAKYzJVeEZ6QVZCZ05WQkFNTURsTnBibWRzWlNCU2IyOTBJRU5CTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdlU1THBiQkV4SXJnZ3MveTRqQUNDSnZETVlJcGZFbVJKS25yODI0dStKZFJiYkpVCnZvN3BHQmprSkc5T25ueUN3OUViQ256eGI1QTNPbHdtLzBvcmNsUGNlaUtQNWFzVUUrbEV2Z05nT3REZDVaVmgKUUlSYjV4a0JYOGFIWFVmNjRncHV2WjE3c1lpc2o2T1BsN2R0VndPamJMOTdKUjd3dWduQ1IzNEs2N2pEbitlSAp5YUZMRDNES2RRdnVzNDZqbXBMMkdHVmE0RGVNNzBpN3pVVTFoUkVaM05qeGI0MmwxKzlJRlo4YVIvb1czWGNwCmFRWnRIdGtkVDRaaDMydTRrZkZEdG9Ea1pTQm1rS3JSVGFZOU9YeWlHWTRXcDJHaThoaExFeVh1RzNJNHVZODgKVUszTmlQcmNDS1ZuamcrS3lHYU5FMUFrd3grb3g2bFdmOE1WUHdJREFRQUJvMk13WVRBT0JnTlZIUThCQWY4RQpCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTdQRHFVMU0vbnlQY3dRNHhFRGNICjN0N25idk13SHdZRFZSMGpCQmd3Rm9BVTdQRHFVMU0vbnlQY3dRNHhFRGNIM3Q3bmJ2TXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUhlcVZnTUVPWWI4eUdtTHd3S3VoMFBwcjJaZy9mRGZtRDd6OGVxN2pocEF6aGpTdENpVAo1RTBjRlJTSkk0VVFmOC8yTjdSa3lJNVhaMEV1Q0E4WmgrWjZpa3JtazVLV1V5Y1pJU1E0eHk5RFo3NmtoVHprCnNCRFhGSFpJNklIZ3Vub214UE1kdW1HOXpaWk9uZmEyNWExcWVjQ0pBYWtlbTFTVmwyNzdtUmVFZjdhZ0JhRUwKUWFiSTA2UUk5dGIvYng2VWg5RERTOXFLU3FwQ3FHQXNWU1d4WXJ5alZBN2VTallIZU8wcTdkRGkyRVZGODA1UApIRCtsWFZtL1htYjA5bmNiaDVEQWVKU3FxQnVEYlEvNWd6SmJHSGdibVVaaFpFWmhnTDNZUFdybGI4ODN4cjh5CnlhQnU5SlZPM2djMXJ5N1ZINTFzKzdSWjI1Qzd1VVJEUUpJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
kind: Secret
metadata:
  name: tls-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: tpm-service
spec:
  internalTrafficPolicy: Local
  selector:
    name: tpm-ds
  ports:
  - name: http-port
    protocol: TCP
    port: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: tpm-service-external
spec:
  type: LoadBalancer
  selector:
    name: tpm-ds
  ports:
  - name: http-port
    protocol: TCP
    port: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpm-service-account
  namespace: default
automountServiceAccountToken: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tpm
spec:
  podSelector:
    matchLabels:
      name: tpm-ds
  ingress:
  - from:
    - podSelector:
        matchLabels:
          allowtpm: "true"
  policyTypes:
    - Ingress
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpm-ds
  namespace: default
  labels:
    k8s-app: tpm-ds
spec:
  selector:
    matchLabels:
      name: tpm-ds
  template:
    metadata:
      labels:
        name: tpm-ds
    spec:
      serviceAccountName: tpm-service-account
      automountServiceAccountToken: true
      containers:
        - name: server
          image: index.docker.io/salrashid123/tpmds@sha256:55f1d40c9d7c21b7acbd8555141f58d1c99013c5f0c82c98d094248700921cbb
          securityContext:
            privileged: true
          ports:
          - containerPort: 50051
            protocol: TCP   
          command:
            - /grpc_attestor
            - --grpcport=:50051
            - --caCertTLS=/certs/root.crt
            - --servercert=/certs/server_crt.pem
            - --serverkey=/certs/server_key.pem
            - --contextsPath=/contexts
            - --eventLogPath=/root/binary_bios_measurements
            - --v=10 
            - -alsologtostderr
          volumeMounts:
            - mountPath: /contexts
              name: contexts-volume
            - mountPath: /certs
              name: certs
              readOnly: true
            - mountPath: /dev/tpm0
              name: tpm
            - mountPath: /root/binary_bios_measurements
              name: eventlog  
      volumes:
      - name: tpm
        hostPath:
          path: /dev/tpm0
      - name: eventlog
        hostPath:
          path: /sys/kernel/security/tpm0/binary_bios_measurements
      - name: contexts-volume
        # hostPath:
        #   path: /data
        emptyDir: {}
      - name: certs
        secret:
          secretName: tls-secrets