apiVersion: v1
data:
  server_crt.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVSRENDQXl5Z0F3SUJBZ0lCTHpBTkJna3Foa2lHOXcwQkFRc0ZBREJYTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVNJd0lBWURWUVFEREJsRgpiblJsY25CeWFYTmxJRk4xWW05eVpHbHVZWFJsSUVOQk1CNFhEVEl5TVRBek1URTBOVE14TlZvWERUSTFNREl3Ck56RTBOVE14TlZvd1ZqRUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQW9NQmtkdmIyZHNaVEVUTUJFR0ExVUUKQ3d3S1JXNTBaWEp3Y21selpURWhNQjhHQTFVRUF3d1lZWFIwWlhOMGIzSXVaWE52WkdWdGIyRndjREl1WTI5dApNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFDTHR1QmY3U0d3ZG1nRE5lRzFvCmpiQ3R0Q1JzdTRBK1ptVWc5UktUSkZvRTkyYXhoY01pblB1SFZqTFZuTEVRa3BpTUhXc3NobUpWaTZXdUlEQkYKcCtRcVJVVUNZdk5Qc0M3cGJNUk5mQ2xqVTkrZy9XRVZhaXEyc3ZRSGszMnpUMDV1N0dWb1hJRU1HYndFWm1KdgprYk1ONlZDWEdiSVlCMzlSc0NucC9vcXpwRVZnSW1oYW10T3RWdC9QaWE4S2xBZ3JUb29SdjZPYmlJVW42UXhXCnRxT2ozelBpcFVsU1dndDhLeHBTVW85UXo1TUdlNDA5ZW4zMDBueDdqaFZyKzhieXdhekxyRmVDODI0ZXRlSVQKOVpkWkxTVThHQWlBd1pva21pZnFWeGxiMnU1QTJhTlk5ZUdWMFdUZWEvYVk5a2p6UFhZcVI1MGVFdjZvL0dzcwo5UUlEQVFBQm80SUJHakNDQVJZd0RnWURWUjBQQVFIL0JBUURBZ2VBTUFrR0ExVWRFd1FDTUFBd0V3WURWUjBsCkJBd3dDZ1lJS3dZQkJRVUhBd0V3SFFZRFZSME9CQllFRkN5SHQxSzlsUmNMZFRmNDF2S1ZSTTU5RkFZdU1COEcKQTFVZEl3UVlNQmFBRkxlNnNBS2g1NzQweHNFRlhHWjQ1YnRUWGFGVU1FUUdDQ3NHQVFVRkJ3RUJCRGd3TmpBMApCZ2dyQmdFRkJRY3dBb1lvYUhSMGNEb3ZMM0JyYVM1bGMyOWtaVzF2WVhCd01pNWpiMjB2WTJFdmRHeHpMV05oCkxtTmxjakE1QmdOVkhSOEVNakF3TUM2Z0xLQXFoaWhvZEhSd09pOHZjR3RwTG1WemIyUmxiVzloY0hBeUxtTnYKYlM5allTOTBiSE10WTJFdVkzSnNNQ01HQTFVZEVRUWNNQnFDR0dGMGRHVnpkRzl5TG1WemIyUmxiVzloY0hBeQpMbU52YlRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxaamNlZVVlRmFqMGFiRHN3eHovU3MzaUVIaGR4RXZUCmxaMnJFempTRUdZVDNNRGRqL09qZHgxYW9WeG1mbmF2dEwrcVlTZDIxZnNzcnZNSjQyajF3S2h2bHFtR0N5TEYKOVRVN1NqSW9zWEJuSXhwS1dLU3lad0pDYmNYV1hTTTEvd05uSkZRNkxSYjlDVXJ0cy9VOWxPMEdhc3N0UkhwUgpqSHFBcTZvV3VhYmcwTjFOc3NTSmxPVVV3MGo5b3RzM1dqMXVOTU1uZ0pOcllEVy82V1haR2h0Y08vbU5obERECm40Z1gwNE9CWWJ0VEp3UXI0TmN5T1o5VjgyUU4walVQdDhZL1hpQmpGZjBhYkJUVlBRaCt5YU96T1plb2s1TTAKaWluV2dLNnNmU0R4Q0RmSEcyMkZHSExtcXlrb0l0TjYvRVB0QWRqTS9QakFoWVlQODdwak9RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ== 
  server_key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRFVJdTI0Ri90SWJCMmEKQU0xNGJXaU5zSzIwSkd5N2dENW1aU0QxRXBNa1dnVDNackdGd3lLYys0ZFdNdFdjc1JDU21Jd2RheXlHWWxXTApwYTRnTUVXbjVDcEZSUUppODArd0x1bHN4RTE4S1dOVDM2RDlZUlZxS3JheTlBZVRmYk5QVG03c1pXaGNnUXdaCnZBUm1ZbStSc3czcFVKY1pzaGdIZjFHd0tlbitpck9rUldBaWFGcWEwNjFXMzgrSnJ3cVVDQ3RPaWhHL281dUkKaFNmcERGYTJvNlBmTStLbFNWSmFDM3dyR2xKU2oxRFBrd1o3alQxNmZmVFNmSHVPRld2N3h2TEJyTXVzVjRMegpiaDYxNGhQMWwxa3RKVHdZQ0lEQm1pU2FKK3BYR1Z2YTdrRFpvMWoxNFpYUlpONXI5cGoyU1BNOWRpcEhuUjRTCi9xajhheXoxQWdNQkFBRUNnZ0VBQU4vTnBINVVKQWN1czdiYlRKV0ExK0trUTBqZmVpeXNDbjU4c3JNd3BZdjAKYk1qcmVZa1FGYlJkL3FveUlnQkRJMDR3ZDZJOGhQenNsdFBTNGt3OTlwUS9ZMWt4TlJOYWRFMVdoaGhQVnhxOApPaVBZQ3BYeGxydUFmMm9pTk52N1Z2RS9Ea2VEQ2xjNEk2RllKYUdKWXdEcFVWay93aW52Sk9yRC9WVklPRlc3CjZPVzlsK0FXZ3FnYzloQXdLLzZsVkxaTjNOSEtYZUd3eUZDazdCdUJRM0tUVWJDdllmMjkxeEhyU2RPNll5L2sKSmdqVlYzM0pRTnZXK2NRKzB6MzliRGdwZ1lIMU9VdmdwUTRkZW5PY1lMaFNFOTlSU2FJcjJOQVlhOXg0Y0VNWQpOT3NDdVR4TG1ZWTJHOWdEbTVTWFRta0tKLy8wQzNqK3ZseFlkREdOMlFLQmdRRHFjeHJ6SmE5N3lTQXZISkg3CjdYTGhjbFl1S2VrVU9BZThUSU9UVVpRQjVvMjR2UFBmdmRvOXJEWkJUY3BFcHk0VmhhbjYzeDdTWHQyaG1mb2EKTUd5eHZiemxMSFFxRlhFcjVRN21XaW5BYThsT3praXdIRktOUUJBUjNBbExwZjZwNDY5cFdLMSs2T0xZVGllVwpvemtRNjFJaFhBNVpTYnZsMkVtWThMMWgzUUtCZ1FEbm9zUVE3M0E3RlFvd2FsaFluRlF1S2R4cDN3Mm94VDZDCnUvVUlpMS8zcHUxMSt0VEJhZlpQWTBKeVVWU1czM3dWMXYvOWV2b25NdXNnTERid1dJcks4b1o3aC94TlRpS0IKZFNBOEtsalZaWmtuQksxNThRSGdrRjFoaU9mQlRobmJHMHVBNzhNMyt3SEdFZTdrSzNIanF1Y2QvTW9kTk5GTAp6QW9taFNlaCtRS0JnQlZYc1NaZFVlSkU1dWNqQks4WWFKTFpZN3NFR2JHN2dBakdObHdjMndwcFFKR0dzZlMyClJiM0RoWlRnVGY5OThKWUkrdlpaaFdiRk9BdlVCbzZIeGYxUU5uZnVXZ3pTc3VDNkUyY280aEFnUDgwcXZqYzUKL05IYStSdUhHbG1Hbk80K1NlT2ZMUHdXbXoveHJXenJJdkRGVzA2cUlLeEVLQlMrWWNUSWRaVUpBb0dBYVlHVwo0c3ZkQjl4R2Z0VUJscUxtS1B6Q082cndrczM4OGhsZ3U5cVlCTHFROEtzbW0wNkRkWmVWblhKMElDQjlhWWs3Cm9wNlFNS2lkdGxMTlYxNU5JYkdrRmNKVDVuWlBlejM1Ujg1V0ZpVW54RUQ2TDAvYWRnbnJydEJvRjRGV2Y1bUkKSTV1U0JQNmN5VFpENU1QeEpTMGtCbUd0UWU1YjRyVjJiaU02Y1NrQ2dZQi9DcW92ZHFlRWpJZ2JtcDBVNTR0bgo5ek1VT0tJT1o5RU5teWJHYTNtbWVzYXZNVHlIS1ZOaDFsaVJ0NFBIMld5MnM5Q1gxT2lYSDl3NGRUS1ZSdVBoCmMxMzgvWFdoaEVESmtPYkxBL0tkdFhEVHFvOUsydWFOTi96Z3lBZnRaREs5NC9TQlVvdU90eTBLZXBkUXovNUkKeGN1NU0wTGZtNmZWc0dMRC9xRFZ3Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  root.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVEVENDQXZXZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREJRTVFzd0NRWURWUVFHRXdKVlV6RVAKTUEwR0ExVUVDZ3dHUjI5dloyeGxNUk13RVFZRFZRUUxEQXBGYm5SbGNuQnlhWE5sTVJzd0dRWURWUVFEREJKRgpiblJsY25CeWFYTmxJRkp2YjNRZ1EwRXdIaGNOTWpJd01UQTVNakl3TlRReldoY05Nekl3TVRBNU1qSXdOVFF6CldqQlhNUXN3Q1FZRFZRUUdFd0pWVXpFUE1BMEdBMVVFQ2d3R1IyOXZaMnhsTVJNd0VRWURWUVFMREFwRmJuUmwKY25CeWFYTmxNU0l3SUFZRFZRUUREQmxGYm5SbGNuQnlhWE5sSUZOMVltOXlaR2x1WVhSbElFTkJNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6UUVTdVlySjVVdlZ6Tmw2SzlITDJ3SWpLcGkxClptVU5ObERvbndJRy84T3FwcHY4TGw1NXVLNUxzUW5QRVBqaXU2ZHhlTzdMSC9ZTVpESVpNWVNuNjI2UUtTNmMKQlE2N1dXSHAyeHZiNHpYSXBqbndMdDZGWCsrcHM4eVpOd1BuVDZ5a3pVVWRUZ3ZEUEh6aXNjcXY4aUJpTkp2MAp6c21UOXN5Wk5mWHlGTU1RVlB2SWxFN2hCNDV4akdHbko1ekhTV3JJWHowaWs0Smg3SUJSaE00TE03a2k3dVZQCnE2MTk1Y0I2M0w5SEh3UnpmcGFHYnVzcHRFeW1SYm5qVFlFcnUveElISDcxSlJsQkpLSTZzNWZ4MWlhQXpPSHcKNCtiUU9zdmZjM2xyNW5zeURPUHVrdm5lM3JMU1VQa2dTWUx0bEV2UGV3cDM1d0hpWGxEc0VnTXM3d0lEQVFBQgpvNEhxTUlIbk1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkCkRnUVdCQlMzdXJBQ29lZStOTWJCQlZ4bWVPVzdVMTJoVkRBZkJnTlZIU01FR0RBV2dCUjhIRnZvUHJNekNaYVMKTXRoL1JML01qSk9ja2pCRkJnZ3JCZ0VGQlFjQkFRUTVNRGN3TlFZSUt3WUJCUVVITUFLR0tXaDBkSEE2THk5dwphMmt1WlhOdlpHVnRiMkZ3Y0RJdVkyOXRMMk5oTDNKdmIzUXRZMkV1WTJWeU1Eb0dBMVVkSHdRek1ERXdMNkF0Cm9DdUdLV2gwZEhBNkx5OXdhMmt1WlhOdlpHVnRiMkZ3Y0RJdVkyOXRMMk5oTDNKdmIzUXRZMkV1WTNKc01BMEcKQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUURDcnJBd2RlUlFNb3Z1MDB3czhJM3JlVUlNRWR0c0Z3TFJTaHUwZ2dWaApHSE1IMXZHRHBkUkpvYVNwQ0dkQ2NQdjFJQTBCa0w2OTY5ZGYxR0RVeFFPV2JpTGFqeVE1UzZmVkZnWi95SWJuCjNTek13N0R1YmlnMmk5eEpvOWxhUHBqampNL2dGNmJCU3hkaG9MVUtMRmYwZTgyRkN1QVBYc2tlaVc3QmMxWEIKM3VpNHhnUE5WejNUSHU4TWE5ei9mVEpSb2hyQzh0MUMvcGFiN1RRcGNRUjZYa1JyWDVTYi9NTTZUbkZldzdzRAo1Y3VGVDdvL0R2YldUNDIvVVAybnVOaTU5MVRJR1lESkJDS0JxbmQwQUg2UnorVlR5ZVJVVnA0ajIxRXh0ekwwCkpLbU4xUytkbVA1VzZQMUVWK3p0RWxsS0VWM04vZTZyNjU1d2xERy8weTdHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
kind: Secret
metadata:
  name: tls-secrets
  namespace: default
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: tpm-service
spec:
  internalTrafficPolicy: Local
  selector:
    name: tpm-ds
  ports:
  - name: http-port
    protocol: TCP
    port: 50051
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tpm-service-external
# spec:
#   type: LoadBalancer
#   selector:
#     name: tpm-ds
#   ports:
#   - name: http-port
#     protocol: TCP
#     port: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpm-service-account
  namespace: default
automountServiceAccountToken: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-tpm
spec:
  podSelector:
    matchLabels:
      name: tpm-ds
  ingress:
  - from:
    - podSelector:
        matchLabels:
          allowtpm: "true"
  policyTypes:
    - Ingress
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tpm-ds
  namespace: default
  labels:
    k8s-app: tpm-ds
spec:
  selector:
    matchLabels:
      name: tpm-ds
  template:
    metadata:
      labels:
        name: tpm-ds
    spec:
      serviceAccountName: tpm-service-account
      automountServiceAccountToken: true
      containers:
        - name: server
          image: index.docker.io/salrashid123/tpmds@sha256:0c1bc5fc06333148adaa7a7a41858d458459da08da9529ae1b815e9e6050d7dd
          securityContext:
            privileged: true
          ports:
          - containerPort: 50051
            protocol: TCP   
          command:
            - /grpc_attestor
            - --grpcport=:50051
            - --caCertTLS=/certs/root.crt
            - --servercert=/certs/server_crt.pem
            - --serverkey=/certs/server_key.pem
            - --contextsPath=/contexts
            - --eventLogPath=/root/binary_bios_measurements
            - --v=10 
            - -alsologtostderr
          volumeMounts:
            - mountPath: /contexts
              name: contexts-volume
            - mountPath: /certs
              name: certs
              readOnly: true
            - mountPath: /dev/tpm0
              name: tpm
            - mountPath: /root/binary_bios_measurements
              name: eventlog  
      volumes:
      - name: tpm
        hostPath:
          path: /dev/tpm0
      - name: eventlog
        hostPath:
          path: /sys/kernel/security/tpm0/binary_bios_measurements
      - name: contexts-volume
        # hostPath:
        #   path: /data
        emptyDir: {}
      - name: certs
        secret:
          secretName: tls-secrets