// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: verifier/verifier.proto

package verifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Verifier_GetEK_FullMethodName              = "/verifier.Verifier/GetEK"
	Verifier_GetAK_FullMethodName              = "/verifier.Verifier/GetAK"
	Verifier_Attest_FullMethodName             = "/verifier.Verifier/Attest"
	Verifier_Quote_FullMethodName              = "/verifier.Verifier/Quote"
	Verifier_ImportBlob_FullMethodName         = "/verifier.Verifier/ImportBlob"
	Verifier_ImportSigningKey_FullMethodName   = "/verifier.Verifier/ImportSigningKey"
	Verifier_NewKey_FullMethodName             = "/verifier.Verifier/NewKey"
	Verifier_Sign_FullMethodName               = "/verifier.Verifier/Sign"
	Verifier_GetGCEEKSigningKey_FullMethodName = "/verifier.Verifier/GetGCEEKSigningKey"
	Verifier_SignGCEEK_FullMethodName          = "/verifier.Verifier/SignGCEEK"
)

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierClient interface {
	GetEK(ctx context.Context, in *GetEKRequest, opts ...grpc.CallOption) (*GetEKResponse, error)
	GetAK(ctx context.Context, in *GetAKRequest, opts ...grpc.CallOption) (*GetAKResponse, error)
	Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error)
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	ImportBlob(ctx context.Context, in *ImportBlobRequest, opts ...grpc.CallOption) (*ImportBlobResponse, error)
	ImportSigningKey(ctx context.Context, in *ImportSigningKeyRequest, opts ...grpc.CallOption) (*ImportSigningKeyResponse, error)
	NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	GetGCEEKSigningKey(ctx context.Context, in *GetGCEEKSigningKeyRequest, opts ...grpc.CallOption) (*GetGCEEKSigningKeyResponse, error)
	SignGCEEK(ctx context.Context, in *SignGCEEKRequest, opts ...grpc.CallOption) (*SignGCEEKResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) GetEK(ctx context.Context, in *GetEKRequest, opts ...grpc.CallOption) (*GetEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEKResponse)
	err := c.cc.Invoke(ctx, Verifier_GetEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) GetAK(ctx context.Context, in *GetAKRequest, opts ...grpc.CallOption) (*GetAKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAKResponse)
	err := c.cc.Invoke(ctx, Verifier_GetAK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) Attest(ctx context.Context, in *AttestRequest, opts ...grpc.CallOption) (*AttestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestResponse)
	err := c.cc.Invoke(ctx, Verifier_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, Verifier_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ImportBlob(ctx context.Context, in *ImportBlobRequest, opts ...grpc.CallOption) (*ImportBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportBlobResponse)
	err := c.cc.Invoke(ctx, Verifier_ImportBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ImportSigningKey(ctx context.Context, in *ImportSigningKeyRequest, opts ...grpc.CallOption) (*ImportSigningKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSigningKeyResponse)
	err := c.cc.Invoke(ctx, Verifier_ImportSigningKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) NewKey(ctx context.Context, in *NewKeyRequest, opts ...grpc.CallOption) (*NewKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewKeyResponse)
	err := c.cc.Invoke(ctx, Verifier_NewKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, Verifier_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) GetGCEEKSigningKey(ctx context.Context, in *GetGCEEKSigningKeyRequest, opts ...grpc.CallOption) (*GetGCEEKSigningKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGCEEKSigningKeyResponse)
	err := c.cc.Invoke(ctx, Verifier_GetGCEEKSigningKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) SignGCEEK(ctx context.Context, in *SignGCEEKRequest, opts ...grpc.CallOption) (*SignGCEEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignGCEEKResponse)
	err := c.cc.Invoke(ctx, Verifier_SignGCEEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
// All implementations should embed UnimplementedVerifierServer
// for forward compatibility.
type VerifierServer interface {
	GetEK(context.Context, *GetEKRequest) (*GetEKResponse, error)
	GetAK(context.Context, *GetAKRequest) (*GetAKResponse, error)
	Attest(context.Context, *AttestRequest) (*AttestResponse, error)
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	ImportBlob(context.Context, *ImportBlobRequest) (*ImportBlobResponse, error)
	ImportSigningKey(context.Context, *ImportSigningKeyRequest) (*ImportSigningKeyResponse, error)
	NewKey(context.Context, *NewKeyRequest) (*NewKeyResponse, error)
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	GetGCEEKSigningKey(context.Context, *GetGCEEKSigningKeyRequest) (*GetGCEEKSigningKeyResponse, error)
	SignGCEEK(context.Context, *SignGCEEKRequest) (*SignGCEEKResponse, error)
}

// UnimplementedVerifierServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifierServer struct{}

func (UnimplementedVerifierServer) GetEK(context.Context, *GetEKRequest) (*GetEKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEK not implemented")
}
func (UnimplementedVerifierServer) GetAK(context.Context, *GetAKRequest) (*GetAKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAK not implemented")
}
func (UnimplementedVerifierServer) Attest(context.Context, *AttestRequest) (*AttestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedVerifierServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedVerifierServer) ImportBlob(context.Context, *ImportBlobRequest) (*ImportBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportBlob not implemented")
}
func (UnimplementedVerifierServer) ImportSigningKey(context.Context, *ImportSigningKeyRequest) (*ImportSigningKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSigningKey not implemented")
}
func (UnimplementedVerifierServer) NewKey(context.Context, *NewKeyRequest) (*NewKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewKey not implemented")
}
func (UnimplementedVerifierServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedVerifierServer) GetGCEEKSigningKey(context.Context, *GetGCEEKSigningKeyRequest) (*GetGCEEKSigningKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGCEEKSigningKey not implemented")
}
func (UnimplementedVerifierServer) SignGCEEK(context.Context, *SignGCEEKRequest) (*SignGCEEKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignGCEEK not implemented")
}
func (UnimplementedVerifierServer) testEmbeddedByValue() {}

// UnsafeVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServer will
// result in compilation errors.
type UnsafeVerifierServer interface {
	mustEmbedUnimplementedVerifierServer()
}

func RegisterVerifierServer(s grpc.ServiceRegistrar, srv VerifierServer) {
	// If the following call pancis, it indicates UnimplementedVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Verifier_ServiceDesc, srv)
}

func _Verifier_GetEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_GetEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetEK(ctx, req.(*GetEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_GetAK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetAK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_GetAK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetAK(ctx, req.(*GetAKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).Attest(ctx, req.(*AttestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ImportBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ImportBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_ImportBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ImportBlob(ctx, req.(*ImportBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ImportSigningKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSigningKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ImportSigningKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_ImportSigningKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ImportSigningKey(ctx, req.(*ImportSigningKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_NewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).NewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_NewKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).NewKey(ctx, req.(*NewKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_GetGCEEKSigningKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGCEEKSigningKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetGCEEKSigningKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_GetGCEEKSigningKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetGCEEKSigningKey(ctx, req.(*GetGCEEKSigningKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_SignGCEEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignGCEEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).SignGCEEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_SignGCEEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).SignGCEEK(ctx, req.(*SignGCEEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Verifier_ServiceDesc is the grpc.ServiceDesc for Verifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Verifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verifier.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEK",
			Handler:    _Verifier_GetEK_Handler,
		},
		{
			MethodName: "GetAK",
			Handler:    _Verifier_GetAK_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _Verifier_Attest_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _Verifier_Quote_Handler,
		},
		{
			MethodName: "ImportBlob",
			Handler:    _Verifier_ImportBlob_Handler,
		},
		{
			MethodName: "ImportSigningKey",
			Handler:    _Verifier_ImportSigningKey_Handler,
		},
		{
			MethodName: "NewKey",
			Handler:    _Verifier_NewKey_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _Verifier_Sign_Handler,
		},
		{
			MethodName: "GetGCEEKSigningKey",
			Handler:    _Verifier_GetGCEEKSigningKey_Handler,
		},
		{
			MethodName: "SignGCEEK",
			Handler:    _Verifier_SignGCEEK_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verifier/verifier.proto",
}
